_BASE_: base.yaml
PROJECT_DIR: runs/mixup_64_64
TRAIN:
  IMAGE_SIZE: 64
  BATCH_SIZE: 16
  GRADIENT_ACCUMULATION_STEPS: 4
  MAX_ITER: 700000
MODEL:
  BASE_DIM: 192
  LAYER_SCALE: [1, 2, 3, 4]
  LAYERS_PER_BLOCK: 3
  LABEL_DIM: 2
